### ISSUE TITLE
选择器能否增加builder参数，好传入复杂对象

### ISSUE THREAD

**Issue by weiwill** [longer96/flutter_pickers#1]
目前只支持List<String>，复杂对象，如List<Map<String, String>或者一个List<model>直接被toString 显示出来，不方便扩展

**Comment by weiwill** [comment]
可以将https://github.com/longer96/flutter_pickers/blob/5b5324889bcc39ee79c5bbd18bebdc8e609d1ce7/lib/more_pickers/route/single_picker_route.dart#L231
这行的`itemBuilder`作为参数暴露出来,包装一下，`Widget Function(T data)`,这样就可以传入任意对象，自己解析了
比如
```
Widget builder(Map<String, String> data) {
 String text = data['id'];
        return Align(
            alignment: Alignment.center,
            child: Text(text,
                style: TextStyle(color: _pickerStyle.textColor, fontSize: _pickerFontSize(text)),
                textAlign: TextAlign.start));
}
```

还有个方便使用的方式是传入解析代码的方法
```
String resolveData(T data) {
  return data['id'];
}
```
https://github.com/longer96/flutter_pickers/blob/5b5324889bcc39ee79c5bbd18bebdc8e609d1ce7/lib/more_pickers/route/single_picker_route.dart#L232
这行改成
`String text = resolveData != null ? resolveData(_data[index]) : _data[index].toString(); `
这种方法更方便，而且可以使用flutter_pickers的整体样式。

期待您的回复，谢谢～

**Comment by longer96** [comment]
非常感谢您的建议，我最近在找工作，不是很空闲，不能及时回复消息。方便的话能留个联系方式吗？我想在了解一下这个问题QAQ thankyou

**Comment by longer96** [comment]
> 目前只支持List<String>，复杂对象，如List<Map<String, String>或者一个List<model>直接被toString 显示出来，不方便扩展

非常感谢您的建议，我最近在找工作，不是很空闲，不能及时回复消息。方便的话能留个联系方式吗？我想在了解一下这个问题QAQ thankyou

**Comment by weiwill** [comment]
> > 目前只支持List，复杂对象，如List<Map<String, String>或者一个List直接被toString 显示出来，不方便扩展
> 
> 非常感谢您的建议，我最近在找工作，不是很空闲，不能及时回复消息。方便的话能留个联系方式吗？我想在了解一下这个问题QAQ thankyou

wx: weijanguo

**Comment by weiwill** [comment]
替代方案
重构对象的 toString()方法，以显示数据
