### ISSUE TITLE
建议增加自定义数据模型

### ISSUE THREAD

**Issue by JoinLi** [longer96/flutter_pickers#10]
目前data只能传入String类型的数组对象，但是往往后端的数据是这样的
[{"id":"1","name":"电压预警"},{"id":"2","name":"电流预警"}]
这时候就不得不获得到数据后，在重新for循环创建一个string数组
这就造成了数据冗余
如果能直接自定义数据模型，可以选择要投喂的对象，那就再好不过了！

**Comment by longer96** [comment]
确实是个好想法
但是选择器最终只能接收string数组，不管怎样还是得解析一次，所以最终将解析的操作交给了用户。
1:  [{"id":"1","name":"电压预警"},{"id":"2","name":"电流预警"}].map((e) => e.name).toList();

2: 模型里面实现toString 方法， 例如[issues1](https://github.com/longer96/flutter_pickers/issues/1)
