### ISSUE TITLE
你好，请问为什么我选中的状态和你默认的不一样呢？

### ISSUE THREAD

**Issue by BatterMan-Li** [longer96/flutter_pickers#12]
我的显示默认状态是一个灰色的圆角矩形，请问我应如何修改做到和你demo默认的样式一致，谢谢
![image](https://user-images.githubusercontent.com/28614345/126030559-29b4eac0-e2a2-42fc-ad36-5edda30111c8.png)

**Comment by longer96** [comment]
你好，由于插件是基于系统CupertinoPicker 编写的，flutter 升级到2.0之后默认样式已经修改为如你的图。
如果你希望修改成之前的样式，我提供一种方案，
1：将控件修改为本地引用
2：找到你需要使用的选着器，比如你地址对应的是：address_picker_route.dart
3：找到CupertinoPicker.builder()  添加你想要的样式。  比如以下

 ```
 Widget cPicker = CupertinoPicker.builder(
        decoration: BoxDecoration(
            border: Border.symmetric(
                horizontal: BorderSide(color: Colors.grey, width: 1.0))),
      ),
```

**Comment by longer96** [comment]
如果有较多的反馈，之后会把该属性提取出来

**Comment by aluo44** [comment]
提取出来其实是最好的, 可以方便大家自定义, 谢谢老板

**Comment by zhangbodreams** [comment]
希望老哥提取出来 ，谢谢

**Comment by longer96** [comment]
新版本增加了 PickerStyle.itemOverlay属性，可以设置

**Comment by stf-android** [comment]
时间选择器 选中的item 要求用 双横线包括，但是 如何去掉 年 月 日 ，三个item之间线的间隔空间？？

**Comment by longer96** [comment]
> 选中的item 要求用 双横线包括，

无法通过设置去除，代码不难，你把项目拉下来，年月日3个item其实就是3个滚动的控件拼接的，你可以修改成想要的样式，然后本地引入你的项目
