### ISSUE TITLE
时间格式不对啊

### ISSUE THREAD

**Issue by guoyutao** [longer96/flutter_pickers#13]
时间为什么是2021-8-2 8:0
正确的应该是：2021-08-02 08:00 啊？

**Comment by longer96** [comment]
您好，选择器用的时间格式是自定义的。因为有的时间不是完整时间，比如时分或只选择月。
你可以拿到选择器的时间，通过DateTime(2011,2,2)初始化时间， 通过DateFormat('yyyy-MM-dd HH:mm')转化成你想要的格式
