### ISSUE TITLE
请问弹出的选择器被弹出的软键盘覆盖了，怎么解决？

### ISSUE THREAD

**Issue by codergzh** [longer96/flutter_pickers#14]
需求要求选择器可以搜索，所以我自定义了一个搜索框，但是软键盘弹出后把选择器盖住了。

**Comment by longer96** [comment]
有图吗？

**Comment by codergzh** [comment]
抱歉我不太会图片。这是修改的代码
`PickerStyle customizeStyle({type}) {
    double menuHeight = 80.h;
    Widget _headMenuView = Container( // 我根据这个改的
        color: Colors.white,
        height: menuHeight,
        padding: EdgeInsets.symmetric(horizontal: 50.w,vertical: 8.h),
        child: TextField(
          decoration: InputDecoration(
            contentPadding: EdgeInsets.only(top: 0, bottom: 0),
            fillColor: Color(0x30cccccc),
            filled: true,
            enabledBorder: OutlineInputBorder(
                borderSide: BorderSide(color: Color(0x00FF0000)),
                borderRadius: BorderRadius.all(Radius.circular(100))),
            hintText: '请搜索注册机构',
            focusedBorder: OutlineInputBorder(
                borderSide: BorderSide(color: Color(0x00000000)),
                borderRadius: BorderRadius.all(Radius.circular(100))),
          ),
        )
    );
}`

**Comment by codergzh** [comment]
抱歉我太会发图片，这是修改的代码
PickerStyle customizeStyle({type}) {
    double menuHeight = 80.h;
    Widget _headMenuView = Container(
        color: Colors.white,
        height: menuHeight,
        padding: EdgeInsets.symmetric(horizontal: 50.w,vertical: 8.h),
        child: TextField(
          decoration: InputDecoration(
            contentPadding: EdgeInsets.only(top: 0, bottom: 0),
            fillColor: Color(0x30cccccc),
            filled: true,
            enabledBorder: OutlineInputBorder(
                borderSide: BorderSide(color: Color(0x00FF0000)),
                borderRadius: BorderRadius.all(Radius.circular(100))),
            hintText: '请搜索注册机构',
            focusedBorder: OutlineInputBorder(
                borderSide: BorderSide(color: Color(0x00000000)),
                borderRadius: BorderRadius.all(Radius.circular(100))),
          ),
        )
    );
}

**Comment by longer96** [comment]
说实话，确实不太好修改，我简单修改了一下（不推荐）
1：把选择器提出来，放到你的布局代码里面
2：通过stack 布局展示选择器

或者自己重新写，感觉这个选择器不太符合你的需求
![IMG_4165](https://user-images.githubusercontent.com/20554776/130431688-b3bbd452-6e93-4ac5-b356-ac5520d09476.PNG)

**Comment by codergzh** [comment]
好的，感谢
