### ISSUE TITLE
案例中的城市选择从从城市获取code 写反了

### ISSUE THREAD

**Issue by yang121hao** [longer96/flutter_pickers#19]
List<String> cityCode =  Address.getCityCodeByName(townName: '四川省', cityName: '成都市', provinceName: '武侯区');

实际上应该是
List<String> cityCode =  Address.getCityCodeByName(townName:  '武侯区', cityName: '成都市', provinceName:'四川省');

**Comment by longer96** [comment]
谢谢老哥，已经改正了  👍🏻
