### ISSUE TITLE
如何获取地区code

### ISSUE THREAD

**Issue by ljh1234** [longer96/flutter_pickers#2]
demo里面的addresspicker中的地区code怎么获取的呢，使用Locations.getTownsCityCode需要引入什么依赖吗，按照你的例子直接使用会报错

**Comment by longer96** [comment]
> demo里面的addresspicker中的地区code怎么获取的呢，使用Locations.getTownsCityCode需要引入什么依赖吗，按照你的例子直接使用会报错

您好，不需要依赖什么  导包就OK，
我文档忘记更新了，方法名已经修改成Address.getCityCodeByName()

不好意思
