### ISSUE TITLE
futurebuilder 中使用picker setState 不起作用

### ISSUE THREAD

**Issue by Sunyuwumengsheng** [longer96/flutter_pickers#20]

**Comment by Sunyuwumengsheng** [comment]
另外是否可以添加取消事件回调。

**Comment by longer96** [comment]
> futurebuilder 中使用picker setState 不起作用 
可以具体一点吗？

刚更新了2.1.6版本  可以设置onCancel  监听取消回调。  
已经提交了，等审核通过就可以使用

**Comment by Sunyuwumengsheng** [comment]
一个表单页面再FutureBuilder 里 使用pickers 时间选择器选择时间 手动调用setState 状态没有发生改变

**Comment by Sunyuwumengsheng** [comment]
将页面拿出来不使用futureBuilder setState 正常
