### ISSUE TITLE
选中的回调position不对

### ISSUE THREAD

**Issue by feierlaiedu** [longer96/flutter_pickers#21]
例如添加数据：aaa、aaa、bbb、ccc、ddd

选中第二个aaa 回调的position也是0 

猜测是遍历集合匹配到第一个pos就返回了？

可否修改为根据实际选中的位置返回pos呢

**Comment by longer96** [comment]
thankyou
单项选择器和多项选择器（无关联）  已经修改了，待会审核通过就可以更新到2.1.7版本
