### ISSUE TITLE
大佬有个问题取消事件和左边按钮事件是同一个回调

### ISSUE THREAD

**Issue by Sunyuwumengsheng** [longer96/flutter_pickers#22]
再取消按钮发生响应做个标志区分保证点击外部消失事件和取消按钮事件可自定。确定回调时间可以增加一个getTime方法返回DateTime

**Comment by longer96** [comment]
点击外部消失事件 和 取消按钮事件 我明天有空了在区分。最近工作任务多 QAQ
回调的时间只能自己转一下  因为有的时间选择器 只有时分，不是标准的时间

**Comment by longer96** [comment]
2.1.8版本可以通过该参数区分
onCancel: (bool isCancel) {
        print('longer >>> 点击了取消,是否是通过点击按钮取消：$isCancel');
},
