### ISSUE TITLE
弹窗选择的左右边距是否可以添加remove掉？

### ISSUE THREAD

**Issue by hfcypm** [longer96/flutter_pickers#23]
Widget bottomSheet = MediaQuery.removePadding(
      context: context,
      removeTop: true,
      child: _PickerContentView(
        data: mData,
        selectData: selectData,
        pickerStyle: pickerStyle,
        route: this,
      ),
    );

**Comment by longer96** [comment]
窗口左右没有边距吧？   你指的边距是那个边距
？

**Comment by hfcypm** [comment]
设置itemOverlay后，选择条目的背景宽度没有填充满整个屏幕的宽度，左右两侧是存在间距的，不确定是否因为bottomSheet左右没有移除边距的问题？MediaQuery.removePadding(...removeLeft: true ..removeRight: true..)，选择的条目距离屏幕左右两端的间距是否可以通过传参的形式去控制？谢谢！

**Comment by longer96** [comment]
不好意思 这几天有点忙，没有及时恢复消息。
确实存在边距，这个建议你fork一下项目，自己根据需求修改

如果是单项选择器，single_picker_route.dart 文件。大约在280行左右。根据需求修改边距

![image](https://user-images.githubusercontent.com/20554776/147052037-1b501ac5-7402-4fc5-80c4-9d32a0f01357.png)
