### ISSUE TITLE
想选择某年某月某日某时之前的时间，需要支持

### ISSUE THREAD

**Issue by PersonalRhp** [longer96/flutter_pickers#25]
“minDate|maxDate 的YMD和HMS 没有关联！ 没有关联” 这个可以给一个可配置的，有这样的需求, 比如我现在就遇到了，想选择某年某月某日某时之前的时间

**Comment by longer96** [comment]
额....   这个还是要点代码量
公司最近任务繁多，抱歉不能添加

date_picker_route.dart 你看这个位置[410行](https://github.com/longer96/flutter_pickers/blob/0aac7225559a03a525e126c7df716062d0c7d05c/lib/time_picker/route/date_picker_route.dart?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L410)
就是改变了年之后， 对应月日 数据的修改。  如果需要加上时分秒，还要多加3个判断  
你可以试试  qaq

**Comment by PersonalRhp** [comment]
OK，我看一下

**Comment by longer96** [comment]
嗯嗯，这个只是滑动年引起的数据变化。
按你的需求  还得在月、日、时、分    都加上判断哦

![image](https://user-images.githubusercontent.com/20554776/147541836-c4acde2a-1589-49be-88f3-9d8233cf72d8.png)
