### ISSUE TITLE
请教如何在选择器外面的套一层变成这样

### ISSUE THREAD

**Issue by A-jiaotailang** [longer96/flutter_pickers#27]
![image](https://user-images.githubusercontent.com/91598000/148046778-e18806c5-9bfd-45ff-acc8-8b495d981019.png)

**Comment by longer96** [comment]
啊   这个变化有点大。
其实控件原理很简单的，就是包装了系统的CupertinoPicker
建议自己fork，拉下来自己按照需求修改

**Comment by longer96** [comment]
![image](https://user-images.githubusercontent.com/20554776/148145243-9c0192fb-3be9-4ec6-b6d1-b8add071fa53.png)
单项选择器 就是一个column  包裹了这些，是不是很简单
