### ISSUE TITLE
时间选择器问题

### ISSUE THREAD

**Issue by JonathanGit** [longer96/flutter_pickers#28]
![image](https://user-images.githubusercontent.com/18020348/149442114-10029545-9f29-4c4d-8fc6-f3bf435b4d24.png)

**Comment by JonathanGit** [comment]
这里少了对day的重置

**Comment by longer96** [comment]
是这样的   day  和 second  列表的滑动不会影响后面的数据变化。  （比如滑动月，可能对应的日 天数会变化）

**Comment by JonathanGit** [comment]
在设置了mindate之后，这里不是处理，滑动day时，hour是不会更新的，这就到时年月日大于mindate时，时不能重置为0-23

**Comment by JonathanGit** [comment]
当不用到minDate时，你的处理是没问题的，但用到mindate时就是有问题的，你可以跑下你的demo，设置mindate为datetime.now，滑动day你就会发现问题了

**Comment by longer96** [comment]
不好意思，确实没有实现该功能。  只有年月日联动， 时分秒联动。
这块实现起来我写的代码有点冗余了，所以没有年月日时分秒的6级联动

抱歉  QAQ
![image](https://user-images.githubusercontent.com/20554776/149444620-b600e3c1-da6f-4c68-adb9-f37a0134a5fd.png)

**Comment by longer96** [comment]
没有想好好的设计模式

**Comment by JonathanGit** [comment]
我改了一版，代码不多，可以解决，暂时先用。待后续多验证

**Comment by JonathanGit** [comment]
我改了一版，代码不多，可以解决，暂时先用。待后续多验证
