### ISSUE TITLE
求PickerStyle里增加textStyle

### ISSUE THREAD

**Issue by EddieChen12** [longer96/flutter_pickers#29]
多项选择器（联动）默认的字体大小是18，还不能改
设计稿的item字体大小是15。。。

PickerStyle里直接增加textStyle最好

**Comment by longer96** [comment]
好的  大兄弟还没有放假呀。
我会老家了  等有电脑就更新一下

**Comment by EddieChen12** [comment]
坚持上班到最后一天，哈哈
ps：立这个flag你就不怕回不来

**Comment by longer96** [comment]
哎  临时增加了pickerStyle   textSize属性，先将就用着哈

**Comment by 18601673727** [comment]
textSize 不设置不行 多种语言下字号不一样大小

**Comment by longer96** [comment]
> textSize 不设置不行 多种语言下字号不一样大小

感谢反馈，建议先修改成本地引用，自己单独修改某一个选择器的textStyle（最近公司任务太多  QAQ）
