### ISSUE TITLE
时间选择器没有更新的bug

### ISSUE THREAD

**Issue by quewen08** [longer96/flutter_pickers#31]
- 文件：date_picker_route.dart
- 位置：line: 391
- 状况：在设置maxDate为当前时间时，更改日期并不会触发时间特别是小时的扩充，只会是当前小时为最大值，这就导致选择前一天的时候，最大时间为当前时间。
- 期望：在修改日期不是当前maxDate时能同步修改hour的范围

**Comment by quewen08** [comment]
**补充当前问题的截图**

![Screenshot_2022-02-16-11-54-23-622](https://user-images.githubusercontent.com/16368595/154193942-cf454352-0bda-4695-86b6-f69448bba0be.jpg)

**Comment by quewen08** [comment]
具体文件内容在：https://github.com/longer96/flutter_pickers/blob/0aac7225559a03a525e126c7df716062d0c7d05c/lib/time_picker/route/date_picker_route.dart#L391

**Comment by longer96** [comment]
是这样的，目前版本还不支持 年月日  和时分秒的联动，功能也不是很复杂，只是需要写很多代码。
最近工作任务繁忙QAQ  后续可能支持
看你的需求只联动到分钟 还是很好添加的  可以先clone 到本地。
可以参考https://github.com/longer96/flutter_pickers/issues/28
