### ISSUE TITLE
你好，能不能提供一个接口动态修改弹框数据

### ISSUE THREAD

**Issue by fuyunmanbu** [longer96/flutter_pickers#33]
例如：时间选择器弹框出来给了个默认时间，能否提供一个接口方便弹框出来后还能动态再次修改这个默认值及其他数据，也就是可以再setState选择器上面的信息。🙏

**Comment by longer96** [comment]
不好意思，最近工作很忙，展示没有时间添加。
我想这个问题应该和 用setState更新dialog 的状态类似。

可以尝试通过其他方式能否临时解决

参考
https://book.flutterchina.club/chapter7/dailog.html#_7-7-4-%E5%AF%B9%E8%AF%9D%E6%A1%86%E7%8A%B6%E6%80%81%E7%AE%A1%E7%90%86
