### ISSUE TITLE
v2.1.9  确定按钮出不来？

### ISSUE THREAD

**Issue by BI7PRK** [longer96/flutter_pickers#39]
![图片](https://user-images.githubusercontent.com/24989210/173234322-a6dc8328-0654-4854-98a9-a3d39c30c277.png)

**Comment by hhc-code** [comment]
同问

**Comment by hhc-code** [comment]
> ![图片](https://user-images.githubusercontent.com/24989210/173234322-a6dc8328-0654-4854-98a9-a3d39c30c277.png)

自定义样式即可
