### ISSUE TITLE
item length太长，字体就直接缩小了，还没有地方设置字体大小的，能加个参数么

### ISSUE THREAD

**Issue by yexiang1994** [longer96/flutter_pickers#4]
item length太长，字体就直接缩小了，还没有地方设置字体大小的，能加个参数么

**Comment by longer96** [comment]
是的，当太长之后会动态设置字体大小，防止显示不完整

之后会加入，如果你现在就需要，可以 本地引入插件，然后搜索插件代码 
`fontSize: _pickerFontSize(text)`
会找到这几个选择器的item 字体样式，对应修改
