### ISSUE TITLE
 多列选择器正常来讲应该就是数组形式，很少用map的这个数据形式与后台接口严重不符，valueId 不能获取

### ISSUE THREAD

**Issue by yrjwcharm** [longer96/flutter_pickers#42]

**Comment by longer96** [comment]
无联动的多项器是数组形式，但是有联动的多项选择器如果用数组  怎么把数据关联起来呢？   比如 四川 对应 [ "成都市", "德阳市"， “宜宾市”  等]

**Comment by yrjwcharm** [comment]
https://user-images.githubusercontent.com/34397383/178113408-5afa377a-9b75-4d94-bb84-7535135bdf7d.mp4

那种我没实现换了种形式 我关闭这个吧
