### ISSUE TITLE
弹出窗太大了，可以自定义大小和显示的位置吗？The dialog is too big, cloud I diy the size and location?

### ISSUE THREAD

**Issue by sunjhtrustmobi** [longer96/flutter_pickers#5]

**Comment by longer96** [comment]
你可以通过自定义PickerStyle  pickerHeight 修改弹窗高度，具体可查看Readme -> [自定义样式](https://github.com/longer96/flutter_pickers/blob/master/example/lib/style_picker_page.dart)

目前还不能修改显示的位置。

**Comment by sunjhtrustmobi** [comment]
> 你可以通过自定义PickerStyle pickerHeight 修改弹窗高度，具体可查看Readme -> [自定义样式](https://github.com/longer96/flutter_pickers/blob/master/example/lib/style_picker_page.dart)
> 
> 目前还不能修改显示的位置。

只能修改高度吗，宽度不能修改吗？

**Comment by longer96** [comment]
很抱歉  目前自定义属性还不支持修改宽度，但是你可以修改为本地引用，然后在build() 方法里面修改宽度

比如 你使用的是单项选择器，进入到 [single_picker_route.dart](https://github.com/longer96/flutter_pickers/blob/master/lib/more_pickers/route/single_picker_route.dart) 文件
大约122行的build

`  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      child: AnimatedBuilder(
        animation: widget.route.animation!,
        builder: (BuildContext context, Widget? child) {
         /// 这里加了一个Padding
          return Padding(
            padding: const EdgeInsets.symmetric(horizontal: 28),
            child: ClipRect(
              child: CustomSingleChildLayout(
                delegate: _BottomPickerLayout(widget.route.animation!.value,
                    pickerStyle: _pickerStyle),
                child: GestureDetector(
                  child: Material(
                    color: Colors.transparent,
                    child: _renderPickerView(),
                  ),
                ),
              ),
            ),
          );
        },
      ),
    );
  }
`

**Comment by longer96** [comment]
```
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      child: AnimatedBuilder(
        animation: widget.route.animation!,
        builder: (BuildContext context, Widget? child) {
          return Padding(
            padding: const EdgeInsets.symmetric(horizontal: 28),
            child: ClipRect(
              child: CustomSingleChildLayout(
                delegate: _BottomPickerLayout(widget.route.animation!.value,
                    pickerStyle: _pickerStyle),
                child: GestureDetector(
                  child: Material(
                    color: Colors.transparent,
                    child: _renderPickerView(),
                  ),
                ),
              ),
            ),
          );
        },
      ),
    );
  }

```

**Comment by sunjhtrustmobi** [comment]
> 很抱歉 目前自定义属性还不支持修改宽度，但是你可以修改为本地引用，然后在build() 方法里面修改宽度
> 
> 比如 你使用的是单项选择器，进入到 [single_picker_route.dart](https://github.com/longer96/flutter_pickers/blob/master/lib/more_pickers/route/single_picker_route.dart) 文件
> 大约122行的build
> 
> ```
> @override
>  Widget build(BuildContext context) {
>    return GestureDetector(
>      child: AnimatedBuilder(
>        animation: widget.route.animation!,
>        builder: (BuildContext context, Widget? child) {
>         /// 这里加了一个Padding
>          return Padding(
>            padding: const EdgeInsets.symmetric(horizontal: 28),
>            child: ClipRect(
>              child: CustomSingleChildLayout(
>                delegate: _BottomPickerLayout(widget.route.animation!.value,
>                    pickerStyle: _pickerStyle),
>                child: GestureDetector(
>                  child: Material(
>                    color: Colors.transparent,
>                    child: _renderPickerView(),
>                  ),
>                ),
>              ),
>            ),
>          );
>        },
>      ),
>    );
>  }
> ```

好的，万分感谢，我去试一下。
