### ISSUE TITLE
多列选择器（非地区选择）如何实现联动效果？

### ISSUE THREAD

**Issue by zhoujia456888** [longer96/flutter_pickers#6]
多列选择器（非地区选择）如何实现联动效果？
项目需求需要先选择年级，然后选择年级下面的班级？多列选择器能否实现联动？
或者地区选择是否可以自定义传入的数据？

**Comment by longer96** [comment]
不好意思，才回复消息  
之前没有联动的功能，一直在计划加上，昨天加班写出来了 ，正在测试
不出意外 下午就能更新
谢谢支持

**Comment by longer96** [comment]
已经更新 2.1.0版本了，
如果还在使用的话，可以查看readme🤣
