### ISSUE TITLE
希望返回应该加入一个下标,或者传入的list集合里给定一个字段,显示数据就从实体类去取这个字段显示

### ISSUE THREAD

**Issue by gaoxu19930112** [longer96/flutter_pickers#8]
返回应该加入一个下标,或者传入的list集合里给定一个字段,显示数据就从实体类去取这个字段显示,否则只能传一个String字符串的list进去,如果我是一个对象列表,有些对象的name值是一样的,我只拿到选中的name,只通过一个name值我怎么能判断这个name值应该对应哪个对象呢

**Comment by longer96** [comment]
> 返回应该加入一个下标,或者传入的list集合里给定一个字段,显示数据就从实体类去取这个字段显示,否则只能传一个String字符串的list进去,如果我是一个对象列表,有些对象的name值是一样的,我只拿到选中的name,只通过一个name值我怎么能判断这个name值应该对应哪个对象呢

感谢建议，  单项、多项选择器  已经在返回数据增加了下标数据
已经提交了 2.1.1版本
使用方法可参考readme文档   注意onChanged，onConfirm
